### ISSUE TITLE
Facing an  OSError ,while trying to download the repo

### ISSUE THREAD

**Issue by hakimkartik** [helpshift/scyllabackup#1]
I tried downloading  an uploaded scylla repo from aws s3 , but i m facing following issue
```
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~]   scyllabackup download -c backup.yml --snapshot 1538550178 --download-dir /mnt1/tmp --schema /mnt1
[2018-10-03 07:04:14,079] ERROR scyllabackup: Schema file /mnt1 already exists, can't download
Traceback (most recent call last):
  File "/usr/bin/scyllabackup", line 11, in <module>
    sys.exit(cli_run_with_lock())
  File "/usr/lib/python2.7/site-packages/scyllabackup/cli.py", line 366, in cli_run_with_lock
    cli.func(cli)
  File "/usr/lib/python2.7/site-packages/scyllabackup/cli.py", line 77, in download_snapshot
    raise OSError(error_code, error_msg)
OSError: [Errno 17] Schema file /mnt1 already exists
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~]
```

fyi 
```
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~] scyllabackup download_db -c  backup.yml  /tmp
[2018-10-03 07:01:39,913] ERROR scyllabackup: DB file already exists at path /tmp, can't download
Traceback (most recent call last):
  File "/usr/bin/scyllabackup", line 11, in <module>
    sys.exit(cli_run_with_lock())
  File "/usr/lib/python2.7/site-packages/scyllabackup/cli.py", line 366, in cli_run_with_lock
    cli.func(cli)
  File "/usr/lib/python2.7/site-packages/scyllabackup/cli.py", line 121, in download_db
    raise OSError(17, error_msg)
OSError: [Errno 17] DB file already exists at path /tmp
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~]
```

```

[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~] ls /mnt1
config  coredump  heap-dumps  logs  resources  scylla  tmp
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~] ls /mnt1/tmp
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~]
```
```
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~] cat backup.yml
---
path: '/mnt1/scylla/data/'
db: 'DB'
provider: s3
nodetool-path: /usr/bin/nodetool
cqlsh-path: /usr/bin/cqlsh
cqlsh-port: 9042
cqlsh-host: 10.0.2.191
prefix: scylla-global-metadata_02-10-2018_backup_test
s3-bucket-name: nqa-scylla-backup
s3-aws-key: Axxxxxxxx
s3-aws-secret: xxxxxxxxx

[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~]
```

```
[$] aws s3api list-objects --bucket nqa-scylla-backup --query 'Contents[].{Key: Key, Size: Size}'
[
    {
        "Key": "scylla-global-metadata_02-10-2018_backup_test/DB",
        "Size": 21299200
    },
    {
        "Key": "scylla-global-metadata_02-10-2018_backup_test/lst_image_classification_details/imageclassificationdetails-f96ecff0964c11e88aad000000000001/lst_image_classification_details-imageclassificationdetails-ka-103880-CRC.db",
        "Size": 10248
    },
```
Can someone please suggest where i am going woring , i m a bit new to python.  
@perfectayush

**Comment by perfectayush** [comment]
@hakimkartik First of all i will advise you to rotate your aws keys, you shouldn't post such secrets publicly.

Secondly, some parameters expect directories, and some other parameters expect file name. This is explicitly mentioned in most places in help. There are a few mistakes I just noticed as mentioned below, I will fix that.

The argument for  `--schema` for the *download* command expects an file path, rather than directory. You are doing the same for `download_db_path` in *download_db* command, passing directory rather than file name. In both these places, you are passing an existing directory as argument, when you should pass the new file name to create the required resource. Passing the right argument should fix your issue.

I noticed that  documentation for help for `download_db_path` is wrong for *download_db* command (a copy mistake). It should be a file name rather than directory. I will fix that.

**Comment by hakimkartik** [comment]
Thanks for the clarification
It worked but then i got stuck at the next step , for downloading data 
```
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~] scyllabackup download --path /mnt1/scylla/data/  --db DB --provider s3 --nodetool-path  /usr/bin/nodetool --cqlsh-path  /usr/bin/cqlsh --cqlsh-port 9042 --cqlsh-host 10.0.2.191 --prefix scylla-global-metadata_02-10-2018_backup_test --s3-bucket-name 'nqa-scylla-backup'  --s3-aws-key 'xxxx'  --s3-aws-secret   'xxxxx'  --snapshot 1538553853 --download-dir /mnt1/tmp2/ --schema /mnt1/tmp2/schema
[2018-10-03 15:16:20,848] ERROR scyllabackup.snapshot: Specified snapshot doesn't exist, please specify a valid snapshot.
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~]
```
```
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~] scyllabackup download --path /mnt1/scylla/data/  --db DB --provider s3 --nodetool-path  /usr/bin/nodetool --cqlsh-path  /usr/bin/cqlsh --cqlsh-port 9042 --cqlsh-host 10.0.2.191 --prefix scylla-global-metadata_02-10-2018_backup_test --s3-bucket-name 'nqa-scylla-backup'  --s3-aws-key 'xxxxx'  --s3-aws-secret   'xxxxxxx'   --download-dir /mnt1/tmp2/ --schema /mnt1/tmp2/schema --latest-before 1538580054
Traceback (most recent call last):
  File "/usr/bin/scyllabackup", line 11, in <module>
    sys.exit(cli_run_with_lock())
  File "/usr/lib/python2.7/site-packages/scyllabackup/cli.py", line 366, in cli_run_with_lock
    cli.func(cli)
  File "/usr/lib/python2.7/site-packages/scyllabackup/cli.py", line 82, in download_snapshot
    args.latest_before, count=1))
StopIteration
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~]
```
I m assuming that value to be passed as snapshot is epoch time at which we triggered the snapshot
i also tried  `--latest-before`
```
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~] scyllabackup download --path /mnt1/scylla/data/  --db DB --provider s3 --nodetool-path  /usr/bin/nodetool --cqlsh-path  /usr/bin/cqlsh --cqlsh-port 9042 --cqlsh-host 10.0.2.191 --prefix scylla-global-metadata_02-10-2018_backup_test --s3-bucket-name 'nqa-scylla-backup'  --s3-aws-key 'xxxxx'  --s3-aws-secret   'xxxxx'   --download-dir /mnt1/tmp2/ --schema /mnt1/tmp2/schema --latest-before 1538438453
Traceback (most recent call last):
  File "/usr/bin/scyllabackup", line 11, in <module>
    sys.exit(cli_run_with_lock())
  File "/usr/lib/python2.7/site-packages/scyllabackup/cli.py", line 366, in cli_run_with_lock
    cli.func(cli)
  File "/usr/lib/python2.7/site-packages/scyllabackup/cli.py", line 82, in download_snapshot
    args.latest_before, count=1))
StopIteration
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:~]
```
Can u plz guide me where i am going wrong @perfectayush

**Comment by perfectayush** [comment]
@hakimkartik I think you are passing the wrong value for --db, it needs to be absolute path of the db file you downloaded from s3. Have you tried running the `list` command successfully?

**Comment by hakimkartik** [comment]
@perfectayush the data got restored but as specified in doc the schema file wasnt created on the path i passed while dowload command ie `--schema /mnt1/tmp2/schema`
```
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:/mnt1] scyllabackup download --path /mnt1/scylla/data/  --db /mnt1/tmp/DB --provider s3 --nodetool-path  /usr/bin/nodetool --cqlsh-path  /usr/bin/cqlsh --cqlsh-port 9042 --cqlsh-host 10.0.2.191 --prefix scylla-global-metadata_02-10-2018_backup_test --s3-bucket-name 'nqa-scylla-backup'  --s3-aws-key 'abc'  --s3-aws-secret   'xabc'   --download-dir /mnt1/tmp2/ --schema /mnt1/tmp2/schema --snapshot 1538466196



[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:/mnt1]
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:/mnt1] ls tmp
DB
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:/mnt1] du -sch tmp2
426G	tmp2
426G	total
[root@nqa-scylla-backup-restore-kartik-test-1-1c 10.0.2.191:/mnt1]```

**Comment by perfectayush** [comment]
@hakimkartik the file should be at /mnt1/tmp2/schema. Also you should `ls` on tmp2 not on tmp. du -sch won't show you the schema file.
